name: Build Docker Image on Push to Master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t my-image:latest .

    # Optional: Save the image as an artifact or push it somewhere
    # For now, this just builds the image on the runner
